name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2016
    steps:
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'citra-vanguard'
        submodules: 'recursive'
    - name: Checkout RTCV peer dependency
      uses: actions/checkout@v2
      with:
        repository: 'ircluzar/RTCV'
        ref: '505'
        path: 'RTCV'
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1.0.2
      with:
        nuget-version: 'latest'
    - name: Restore Nuget packages in RTCV
      run: nuget restore '.\RTCV\'
    - name: Make directory for citra output
      shell: powershell
      run: New-Item -ItemType directory -Path ${{runner.workspace}}\citra-vanguard\citra-vanguard\build
    - name: Citra prebuild # "Visual Studio 16 2019" doesn't work
      shell: cmd
      run: |
        cd ${{runner.workspace}}\citra-vanguard\citra-vanguard\build
        cmake -G "Visual Studio 15 2017 Win64" -DCITRA_USE_BUNDLED_QT=1 -DCITRA_USE_BUNDLED_SDL2=1 -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON -DUSE_DISCORD_PRESENCE=ON -DENABLE_MF=ON -DENABLE_FFMPEG_VIDEO_DUMPER=ON .. 2>&1 && exit 0
    - name: Citra Build
      run: |
        cd ${{runner.workspace}}\citra-vanguard\citra-vanguard\build
        & "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\MSBuild.exe" citra.sln
    