name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'citra-vanguard'
        submodules: 'recursive'
    - name: Checkout RTCV peer dependency
      uses: actions/checkout@v2
      with:
        repository: 'ircluzar/RTCV'
        ref: '505'
        path: 'RTCV'
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1.0.2
      with:
        nuget-version: 'latest'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Restore Nuget packages in RTCV
      run: nuget restore '.\RTCV\'
    - name: Create build directory
      working-directory: ${{runner.workspace}}\citra-vanguard\citra-vanguard
      run: New-Item -ItemType Directory -Path build
    - name: Citra prebuild
      run: |
        cd citra-vanguard\build
        cmake ..
    - name: Citra build
      run: |
        cd citra-vanguard\build
        msbuild citra.sln
