name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2016
    steps:
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'citra-vanguard'
        submodules: 'recursive'
    - name: Checkout RTCV peer dependency
      uses: actions/checkout@v2
      with:
        repository: 'ircluzar/RTCV'
        ref: '505'
        path: 'RTCV'
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1.0.2
      with:
        nuget-version: 'latest'
    - name: Restore Nuget packages in RTCV
      run: nuget restore '.\RTCV\'
    - name: Citra prebuild
      working-directory: ${{runner.workspace}}\citra-vanguard
      run: cmake -G "Visual Studio 15 2017 Win64" -DCITRA_USE_BUNDLED_QT=1 -DCITRA_USE_BUNDLED_SDL2=1 -DCITRA_ENABLE_COMPATIBILITY_REPORTING=${COMPAT} -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON -DUSE_DISCORD_PRESENCE=ON -DENABLE_MF=ON -DENABLE_FFMPEG_VIDEO_DUMPER=ON .\citra-vanguard\
